name: flutter_lab
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0 # Навигация
  get_it: ^9.0.5 # Dependency injection
  talker: ^5.0.2 # Логгер
  talker_flutter: ^5.0.2
  dio: ^5.0.0
  bloc: ^9.1.0       # BLoC паттерн
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  share_plus: ^12.0.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  bloc_test: ^10.0.0   # Для тестирования BLoC

flutter:
  uses-material-design: true
  assets:
  - assets/images/
